# The Docker image that will be used to build your app
image: node
# Functions that should be executed before the build script is run
before_script:
  - yarn install
pages:
  variables:
    CI: "false"
  script:
    - BUILD_PATH='./build/stg' REACT_APP_ENV=stg PUBLIC_URL=https://sentry.pages.myteksi.net/mesh/smdi/smi-web/stg yarn build
    - BUILD_PATH='./build/prd' REACT_APP_ENV=prd PUBLIC_URL=https://sentry.pages.myteksi.net/mesh/smdi/smi-web/prd yarn build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - build
  publish: build
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
